# Generated by Django 4.0.2 on 2023-01-19 01:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_userprofile_qr_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorshipRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('P', 'Pending'), ('A', 'Accepted'), ('R', 'Rejected')], default='P', max_length=1, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('approvee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instructorship_request', to=settings.AUTH_USER_MODEL)),
                ('requestee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_instructorship_request', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
