# Generated by Django 4.0.2 on 2023-03-06 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_instructorshiprequest_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='lrn',
            field=models.CharField(default='', max_length=12, null=True),
        ),
    ]
